# Generated by Django 6.0.5 on 2026-05-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TITULAR', 'Titular'), ('SUPLENTE', 'Suplente')], default='TITULAR', max_length=10)),
            ],
            options={
                'verbose_name': 'Asignación Profesor',
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('sesiones_semanales', models.PositiveSmallIntegerField(default=2)),
                ('duracion_sesion_h', models.PositiveSmallIntegerField(default=2)),
                ('tipo_grupo', models.CharField(choices=[('TEORIA', 'Teoría'), ('PRACTICAS', 'Prácticas'), ('LABORATORIO', 'Laboratorio')], default='TEORIA', max_length=15)),
                ('es_transversal', models.BooleanField(default=False)),
                ('semestre', models.PositiveSmallIntegerField(choices=[(1, 'Primero'), (2, 'Segundo')])),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='AsignaturaTitulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_optativa', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Asignatura por Titulación',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(choices=[('CREACION', 'Creación'), ('EDICION', 'Edición'), ('BORRADO', 'Borrado'), ('APROBACION', 'Aprobación'), ('RECHAZO', 'Rechazo'), ('ESTADO', 'Cambio de Estado')], max_length=15)),
                ('severidad', models.CharField(choices=[('INFO', 'Información'), ('WARN', 'Advertencia'), ('ERROR', 'Error'), ('CRITICAL', 'Crítico')], default='INFO', max_length=10)),
                ('modelo_afectado', models.CharField(max_length=50)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('valor_anterior', models.JSONField(blank=True, null=True)),
                ('valor_nuevo', models.JSONField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('codigo_error', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(choices=[('TEORIA', 'Aula de Teoría'), ('LABORATORIO', 'Laboratorio'), ('SEMINARIO', 'Seminario')], default='TEORIA', max_length=15)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
            },
        ),
        migrations.CreateModel(
            name='CursoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('PLANIFICACION', 'En planificación'), ('ACTIVO', 'Activo'), ('CERRADO', 'Cerrado')], default='PLANIFICACION', max_length=15)),
                ('matriculacion_abierta', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Curso Académico',
                'verbose_name_plural': 'Cursos Académicos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo', models.CharField(choices=[('PREFERENTE', 'Disponibilidad preferente'), ('DISPONIBLE', 'Disponible'), ('INDISPONIBLE', 'Bloqueo / Indisponible')], default='DISPONIBLE', max_length=15)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Disponibilidad Profesor',
                'verbose_name_plural': 'Disponibilidades Profesores',
            },
        ),
        migrations.CreateModel(
            name='FranjaHoraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('turno', models.CharField(choices=[('MANIANA', 'Mañana'), ('TARDE', 'Tarde')], max_length=10)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Franja Horaria',
                'verbose_name_plural': 'Franjas Horarias',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_matricula', models.DateTimeField(auto_now_add=True)),
                ('tiene_conflicto', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
            },
        ),
        migrations.CreateModel(
            name='NivelCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField()),
                ('es_ultimo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Nivel de Curso',
                'verbose_name_plural': 'Niveles de Curso',
                'ordering': ['titulacion', 'anio'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INFO', 'Informativa'), ('ADVERTENCIA', 'Advertencia'), ('ERROR', 'Error'), ('EXITO', 'Éxito')], default='INFO', max_length=15)),
                ('motivo', models.CharField(choices=[('CAMBIO_AULA', 'Cambio de aula'), ('CAMBIO_HORARIO', 'Cambio de horario'), ('CAMBIO_PROFESOR', 'Cambio de profesor'), ('CONFLICTO', 'Conflicto detectado'), ('APROBACION', 'Horario aprobado'), ('RECHAZO', 'Horario rechazado')], max_length=20)),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Sesión',
                'verbose_name_plural': 'Sesiones',
            },
        ),
        migrations.CreateModel(
            name='Titulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('GRADO', 'Grado'), ('DOBLE_GRADO', 'Doble Grado')], default='GRADO', max_length=15)),
                ('duracion_anios', models.PositiveSmallIntegerField(default=4)),
                ('permite_maniana', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Titulación',
                'verbose_name_plural': 'Titulaciones',
            },
        ),
    ]
