# Generated by Django 6.0.5 on 2026-05-23 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('login', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionprofesor',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.perfilprofesor'),
        ),
        migrations.AddField(
            model_name='asignacionprofesor',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.asignatura'),
        ),
        migrations.AddField(
            model_name='asignaturatitulacion',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.asignatura'),
        ),
        migrations.AddField(
            model_name='auditoriahorario',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignacionprofesor',
            name='curso_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cursoacademico'),
        ),
        migrations.AddField(
            model_name='disponibilidadprofesor',
            name='curso_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cursoacademico'),
        ),
        migrations.AddField(
            model_name='disponibilidadprofesor',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='login.perfilprofesor'),
        ),
        migrations.AlterUniqueTogether(
            name='franjahoraria',
            unique_together={('dia_semana', 'hora_inicio', 'hora_fin')},
        ),
        migrations.AddField(
            model_name='horario',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='horario',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='horario',
            name='curso_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cursoacademico'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.perfilalumno'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.asignatura'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='curso_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cursoacademico'),
        ),
        migrations.AddField(
            model_name='horario',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nivelcurso'),
        ),
        migrations.AddField(
            model_name='asignaturatitulacion',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nivelcurso'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sesion',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.asignatura'),
        ),
        migrations.AddField(
            model_name='sesion',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aula'),
        ),
        migrations.AddField(
            model_name='sesion',
            name='franja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.franjahoraria'),
        ),
        migrations.AddField(
            model_name='sesion',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='core.horario'),
        ),
        migrations.AddField(
            model_name='sesion',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.perfilprofesor'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='sesion_afectada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sesion'),
        ),
        migrations.AddField(
            model_name='nivelcurso',
            name='titulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles', to='core.titulacion'),
        ),
        migrations.AddField(
            model_name='horario',
            name='titulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.titulacion'),
        ),
        migrations.AddField(
            model_name='asignaturatitulacion',
            name='titulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.titulacion'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='titulaciones',
            field=models.ManyToManyField(related_name='asignaturas', through='core.AsignaturaTitulacion', to='core.titulacion'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacionprofesor',
            unique_together={('profesor', 'asignatura', 'curso_academico')},
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('alumno', 'asignatura', 'curso_academico')},
        ),
        migrations.AlterUniqueTogether(
            name='sesion',
            unique_together={('aula', 'franja', 'horario'), ('profesor', 'franja', 'horario')},
        ),
        migrations.AlterUniqueTogether(
            name='nivelcurso',
            unique_together={('titulacion', 'anio')},
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('titulacion', 'nivel', 'curso_academico')},
        ),
        migrations.AlterUniqueTogether(
            name='asignaturatitulacion',
            unique_together={('asignatura', 'titulacion', 'nivel')},
        ),
    ]
