# Generated by Django 6.0.5 on 2026-05-25 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestriccionPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FRANJA_BLOQUEADA', 'Bloquear franja horaria completa'), ('ASIG_DIA_EXCLUIDO', 'Excluir asignatura de un día'), ('ASIG_DIA_PREFERIDO', 'Día preferido para asignatura')], max_length=25)),
                ('descripcion', models.CharField(blank=True, help_text='Etiqueta descriptiva (opcional)', max_length=200)),
                ('dia_semana', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('asignatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.asignatura')),
                ('franja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.franjahoraria')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricciones_personalizadas', to='core.horario')),
            ],
            options={
                'verbose_name': 'Restricción personalizada',
                'verbose_name_plural': 'Restricciones personalizadas',
                'ordering': ['tipo', 'creado_en'],
            },
        ),
    ]
