# Generated by Django 6.0.5 on 2026-05-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_restriccion_personalizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadprofesor',
            name='periodo',
            field=models.CharField(choices=[('T1', 'Solo Trimestre 1'), ('T2', 'Solo Trimestre 2'), ('ANUAL', 'Anual (todo el curso)')], default='ANUAL', max_length=5),
        ),
    ]
