# Generated by Django 6.0.5 on 2026-05-25 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_disponibilidad_add_periodo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sesion',
            unique_together={('aula', 'franja', 'horario')},
        ),
    ]
